{application,finch,
             [{applications,[kernel,stdlib,elixir,logger,mint,castore,
                             nimble_pool,nimble_options,telemetry,mime]},
              {description,"An HTTP client focused on performance."},
              {modules,['Elixir.Finch','Elixir.Finch.Conn',
                        'Elixir.Finch.Error','Elixir.Finch.HTTP1.Pool',
                        'Elixir.Finch.HTTP2.Pool',
                        'Elixir.Finch.HTTP2.RequestStream',
                        'Elixir.Finch.MintHTTP1','Elixir.Finch.Pool',
                        'Elixir.Finch.PoolManager','Elixir.Finch.Request',
                        'Elixir.Finch.Response','Elixir.Finch.SSL',
                        'Elixir.Finch.Telemetry']},
              {registered,[]},
              {vsn,"0.15.0"}]}.
