use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

config :crow_web, CrowWeb.Endpoint,
  url: [host: "CROW", port: 5070],
  cache_static_manifest: "priv/static/cache_manifest.json"
  server: true,
  root: ".",

config :crow_web, CrowWeb.Endpoint,
  http: [:inet6, port: String.to_integer(System.get_env("PORT") || "5030")],
  secret_key_base: "secretkey"

config :crow_data, CrowData.Repo,
  username: "postgres",
  password: "postgres",
  database: "crow_data_prod",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10
