{application,tailwind,
             [{applications,[kernel,stdlib,elixir,logger,castore]},
              {description,"Mix tasks for installing and invoking tailwind"},
              {modules,['Elixir.Mix.Tasks.Tailwind',
                        'Elixir.Mix.Tasks.Tailwind.Install',
                        'Elixir.Tailwind']},
              {registered,[]},
              {vsn,"0.2.0"},
              {mod,{'Elixir.Tailwind',[]}},
              {env,[{default,[]}]}]}.
